name: Check

on: [ push, pull_request ]

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Based on https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: Cache Gradle caches and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            .gradle
            app/build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Cache appauth build
        uses: actions/cache@v3
        with:
          path: |
            appauth/library/build
          key: ${{ runner.os }}-appauth-${{ hashFiles('.git/modules/appauth/HEAD') }}
          restore-keys: |
            ${{ runner.os }}-appauth-

      - name: Cache ics-openvpn build
        id: cache-ics-openvpn
        uses: actions/cache@v3
        with:
          path: |
            ics-openvpn/.gradle
            ics-openvpn/main/build
            ics-openvpn/main/.cxx
          key: ${{ runner.os }}-ics_openvpn_2-${{ hashFiles('.git/modules/ics-openvpn/HEAD') }}

      - if: ${{ steps.cache-ics-openvpn.outputs.cache-hit == 'true' }}
        # For unknown reason, ninja always rebuilds, so force use of cache
        name: Build app with ics-openvpn cache
        run: |
          ./gradlew app:assembleBasicRelease app:assembleBasicDebugAndroidTest \
          --build-cache --warning-mode all \
          -x :ics-openvpn-main:configureCMakeRelWithDebInfo[arm64-v8a] \
          -x :ics-openvpn-main:buildCMakeRelWithDebInfo[arm64-v8a] \
          -x :ics-openvpn-main:configureCMakeRelWithDebInfo[armeabi-v7a] \
          -x :ics-openvpn-main:buildCMakeRelWithDebInfo[armeabi-v7a] \
          -x :ics-openvpn-main:configureCMakeRelWithDebInfo[x86] \
          -x :ics-openvpn-main:buildCMakeRelWithDebInfo[x86] \
          -x :ics-openvpn-main:configureCMakeRelWithDebInfo[x86_64] \
          -x :ics-openvpn-main:buildCMakeRelWithDebInfo[x86_64] \
          -x :ics-openvpn-main:externalNativeBuildUiRelease \
          -x :ics-openvpn-main:packageUiReleaseResources \
          -x :ics-openvpn-main:compileUiReleaseJavaWithJavac \
          -x :ics-openvpn-main:configureCMakeDebug[x86_64] \
          -x :ics-openvpn-main:buildCMakeDebug[x86_64] \
          -x :ics-openvpn-main:buildCMakeDebug[arm64-v8a] \
          -x :ics-openvpn-main:buildCMakeDebug[armeabi-v7a] \
          -x :ics-openvpn-main:buildCMakeDebug[x86]

      - if: ${{ steps.cache-ics-openvpn.outputs.cache-hit != 'true' }}
        name: Build app
        run: |
          sudo apt-get update
          sudo apt-get -y install swig ninja-build cmake
          ./gradlew app:assembleBasicRelease app:assembleBasicDebugAndroidTest \
          --build-cache --warning-mode all
